# Generated by Django 5.1.1 on 2024-10-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_admin_rename_firstname_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
