# Generated by Django 5.1.1 on 2024-10-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_admin_confirm_password_appointment_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
