# Generated by Django 5.1.1 on 2024-10-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_admin_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
    ]
