# Generated by Django 5.1.1 on 2024-11-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_created_at_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='appointment',
        ),
    ]
