# Generated by Django 5.1.1 on 2024-11-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_feedback_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_night',
            new_name='price_per_hour',
        ),
    ]
