# Generated by Django 5.1.1 on 2024-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_price_per_night_room_price_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='room',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='room',
            field=models.ManyToManyField(to='app.room'),
        ),
    ]
